config/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

app_name = 'mailer'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailer.urls', namespace='mailer')),
    path('users/', include('users.urls', namespace='users',)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailer/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailer.apps import MailerConfig
from mailer.views import MailingListView, MailingDetailView, MailingUpdateView, MailingCreateView, MailingDeleteView, \
    ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, ClientDetailView, MailingLogListView, \
    MailingDeactivateView, MainView

app_name = MailerConfig.name

urlpatterns = [
    path('mailings/', MailingListView.as_view(),  name='mailing_list'),
    path('<int:pk>', MailingDetailView.as_view(),  name='mailing'),
    path('create/', MailingCreateView.as_view(),  name='create'),
    path('update/<int:pk>', MailingUpdateView.as_view(),  name='update'),
    path('delete/<int:pk>', MailingDeleteView.as_view(),  name='delete'),
    path('deactivate/<int:pk>', MailingDeactivateView.as_view(),  name='deactivate'),

    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('clients/<int:pk>', ClientDetailView.as_view(), name='client'),
    path('clients/create/', ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('clients/delete/<int:pk>', ClientDeleteView.as_view(), name='delete_client'),
    path('<int:pk>/logs', MailingLogListView.as_view(),  name='mailing_logs'),

    path('', cache_page(60)(MainView.as_view()),  name='main'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, EmailConfirmationSentView, \
    UserConfirmEmailView, EmailConfirmedView, EmailConfirmationFailedView, UserListView, UserBlockView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),

    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    path('list', UserListView.as_view(), name='list'),
    path('block/<int:pk>', UserBlockView.as_view(), name='block'),

]

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class BlogPost(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    content = models.TextField(verbose_name='содержимое')
    preview = models.ImageField(upload_to='blog_images/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    view_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'пост'
        verbose_name_plural = 'посты'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='почта')
    is_verified = models.BooleanField(default=False, verbose_name='верифицирован')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            (
                'block',
                'Can block users'
            ),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from mailer.forms import StyleFormMixin
from users.models import User


class UserForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

blog/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.contrib.auth.models import Group

from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, TemplateView, ListView, RedirectView

from config import settings
from users.forms import UserForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'

    def form_valid(self, form):
        user = form.get_user()

        if not user.is_verified:
            messages.error(self.request, 'Ваш адрес электронной почты не подтвержден.')
            return self.form_invalid(form)

        return super().form_valid(form)


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        user = form.save()

        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={'uidb64': uid, 'token': token})
        send_mail(
            'Подтвердите свой электронный адрес',
            f'''Пожалуйста, перейдите по следующей ссылке, чтобы подтвердить свой адрес электронной почты: 
            http://127.0.0.1:8000{activation_url}''',
            settings.EMAIL_HOST_USER,
            [user.email],
            fail_silently=False,
        )
        return redirect('users:email_confirmation_sent')


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_verified = True
            user.save()
            login(request, user)
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmationSentView(TemplateView):
    template_name = 'users/email_confirmation_sent.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Письмо активации отправлено'
        return context


class EmailConfirmedView(TemplateView):
    template_name = 'users/email_confirmed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес активирован'
        return context


class EmailConfirmationFailedView(TemplateView):
    template_name = 'users/email_confirmation_failed.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ваш электронный адрес не активирован'
        return context


class UserListView(ListView):
    model = User

    def get_queryset(self):
        managers_group = Group.objects.get(name='manager')
        return User.objects.exclude(groups=managers_group)


class UserBlockView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        user = User.objects.get(pk=self.kwargs['pk'])
        user.is_active = False
        user.save()
        return reverse_lazy('users:list')

users/templates/users/email_confirmation_failed.html
{% extends "mailer/base.html" %}

{% block content %}

<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">Ошибка подтверждения по электронной почте</h4>
    <p>Ссылка для подтверждения по электронной почте недействительна или срок ее действия истек. Пожалуйста, зарегистрируйтесь снова.</p>
</div>
{% endblock %}

users/templates/users/email_confirmation_sent.html
{% extends "mailer/base.html" %}

{% block content %}

<div class="alert alert-info" role="alert">
    <h4 class="alert-heading">Письмо подтверждения отправлено!</h4>
    <p>
        На ваш адрес электронной почты было отправлено письмо с подтверждением. Пожалуйста, проверьте свою электронную почту и нажмите на ссылку подтверждения, чтобы завершить регистрацию.
        Если письмо не пришло, проверьте папку спам.
    </p>
</div>
{% endblock %}

users/templates/users/email_confirmed.html
{% extends "mailer/base.html" %}

{% block content %}

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Электронная почта подтверждена</h4>
    <p>Ваш адрес электронной почты успешно подтвержден. Спасибо за регистрацию!</p>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailer/base.html' %}
{% block content %}
<main>
<div class="row justify-content-center">
    <div class="col-4">
        <div class="card mt-4 mb-4 box-shadow">
            <div class="card-header text-center">
                <h4 class="my-0 font-weight-normal">Вход</h4>
            </div>
            <div class="card-body m-3">
                {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Подтвердить</button>
                </form>
            </div>
        </div>
    </div>
</div>
</main>
{% endblock %}

users/templates/users/register.html
{% extends 'mailer/base.html' %}
{% block content %}

<div class="row justify-content-center">
    <div class="col-8">
        <div class="card mt-4 mb-4 box-shadow">
            <div class="card-header text-center">
                <h4 class="my-0 font-weight-normal">Регистрация</h4>
            </div>
            <div class="card-body m-3">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'mailer/base.html' %}
{% block content %}
<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Пользователи</h1>
                <a href="{% url 'mailer:mailing_list' %}" class="btn btn-secondary my-2">Рассылки</a>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                {% for object in object_list %}
                <div class="col-4">
                    <div class="card shadow-sm mb-3">
                        <div class="card-header">Пользователь {{ object.email }}
                        </div>

                        <div class="card-body">
                            {% if object.is_verified %}
                            <p>Почта подтверждена</p>
                            {% else %}
                            <p>Почта не подтверждена</p>
                            {% endif %}
                            {% if object.is_active %}
                            <p>Активен</p>
                            {% else %}
                            <p>Заблокирован</p>
                            {% endif %}
                            {% if perms.users.block and object.is_active %}
                            <form action="{% url 'users:block' object.pk %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-outline-danger">Заблокировать</button>
                            </form>
                                {% endif %}
                        </div>

                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>

</main>
{% endblock %}